config/routes.rb
Rails.application.routes.draw do
  
  #root screen
  root to: "elections#index"

  #GET /about
  get "about", to: "about#index"

  get "sign_up", to: "registrations#new"

  post "sign_up", to: "registrations#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in", to: "sessions#new"

  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password

  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"

  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"

  patch "password/reset/edit", to: "password_resets#update"

  get "create", to: "elections#new"

  get "search/elections", to: "elections#search"

  post "create", to: "elections#create"

  get "create/candidates", to: "candidates#new"
  post "create/candidates", to: "candidates#create"
  post "create/candidates", to: "candidates#finish"
  get "view/candidates", to: "candidates#view"

  put "like", to: "candidates#upvote"
  put "unlike", to: "candidates#downvote"

  get "view/elections", to: "elections#view"

  get "select/elections", to: "elections#select"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
#name:string 
#image:string 
#score:integer

class Candidate < ApplicationRecord
    acts_as_votable
    belongs_to :election

    validates :name, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/election.rb
#title:string 
#created_by:string 
#ispublic:boolean 
#participants:string

class Election < ApplicationRecord
    has_many :candidates, dependent: :destroy

    validates :title, presence: true

    def getcreatedby(user)
        self.created_by = user
    end
end

app/models/user.rb
#email:string
#password_digest:string
#password:string virtual
#password_confirmation:string virtual


class User < ApplicationRecord
    
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }

    acts_as_voter
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "Sign in to Complete Action!" if Current.user.nil?
    end

    def setsessionelectionid
        session[:election_id] = nil
    end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

before_action :set_candidate, only: [:upvote, :downvote]

    def new
        @candidate = Candidate.new
        if session[:election_id]
            if nil !=session[:election_id]
                @election = Election.find(session[:election_id])
            end
        else
            redirect_to root_path, alert: "Something was wrong"
        end
    end

    def create
        @candidate = Candidate.new(candidate_params)
        @candidate.election_id = session[:election_id]
        @candidate.score = 0
        if @candidate.save
            flash[:alert] = "Created Candidate: " + @candidate.name 
            #render :new 
            redirect_to create_candidates_path
        else
            render :new
        end
    end

    def finish
        session[:election_id] = nil
        redirect_to root_path, notice: "Successfully created Election!"
    end

    def view 

        @currentcandidates = Candidate.all.where(election_id: session[:election_id]) 
        @theelection = Election.all.find(@currentcandidates.first.election_id)
        
    end

    def upvote
        @candidate.upvote_from Current.user
        redirect_to view_candidates_path
    end

    def downvote
        @candidate.downvote_from Current.user
        redirect_to view_candidates_path
    end

    private
    def set_candidate
        @candidate = Candidate.find(params[:format])
    end

    def candidate_params
        params.require(:candidate).permit(:name, :image)
    end

end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
    
    before_action :require_user_logged_in!, only: [:create, :new, :view]
    before_action :set_election, only: [:select]
    before_action :index, only: [:search]

    def index
       
    end

    def search

        @searchterm = Election.where(["title LIKE ?","%#{params[:search]}%"])
        
        @searchelections = Election.all.where(title: @searchterm) 
        
    end

    def new
        @election = Election.new
    end

    def create
        @election = Election.new(election_params)
        @election.created_by = Current.user.email
        if @election.save
            session[:election_id] = @election.id
            redirect_to create_candidates_path, notice:"Created Election"
        else
            flash[:alert] = "Something was wrong"
            render :new 
        end
    end

    def view
        
        @publicelections = Election.all.where(ispublic: true)

        @createdbyelections = Election.all.where(created_by: Current.user.email)
        
        @privelections = Election.all.where(ispublic: false)
        @privelections.each do |election|
            if election.participants.include? Current.user.email
                @ans.add(election)
            else
                @ans = Election.new
            end
        end
    end

    def select
        session[:election_id] = @Election.id
        redirect_to view_candidates_path
    end

    private
    def set_election
        @Election = Election.find(params[:format])
    end

    def election_params
        params.require(:election).permit(:title, :ispublic, :participants)
        #params.created_by =  Current.user.email
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

def new
end

def create
    @user = User.find_by(email: params[:email])

    if @user.present?
        #send email
        PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: "We have sent a reset link to the specified Email!"
end

def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again"
end

def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
        redirect_to sign_in_path, notice: "Password Updated!"
    else
        render :edit
    end
end

def password_params
    params.require(:user).permit(:password, :password_confirmation)
end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit

    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated"
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else
            render :new
        end

    end

    private
    def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end

    def new

    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in Successful"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/candidates/new.html.erb
<h1>Create A New Candidate</h1>
<% @election %>
<%= form_with model: @candidate, url: create_candidates_path do |form| %>

    <% if form.object.errors.any? %>  
        <div class="alert alert-danger">
            <% @candidate.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <%end%>

   <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", placeholder: "Candidate Name" %>
    </div>
    <div class="mb-3">
        <%= form.label "Image URL" %>
        <h6>this resourse will be loaded in the Election view</h6>
        <%= form.text_field :image, class: "form-control", placeholder: "candidateImage/url" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Create", class: "btn btn-primary"%>
    </div>

<% end %>

<div class="mb-3">
    <%= link_to "Finish!", view_candidates_path, class: "btn btn-primary" %>
</div>

app/views/candidates/view.html.erb
<div>
<h1><%= @theelection.title %></h1>
<div>

<% @currentcandidates.each do |candidate| %>

<div class="card text-center" style="width: 20rem; margin: 10px; float:left;">
  <img class="card-img-top" src=<%= candidate.image %> alt="Card image cap" style="width:300px;height:300px;">
  <div class="card-body">
    <h5 class="card-title"><%= candidate.name %></h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= candidate.get_upvotes.size %></li>
    </ul>
  </div>
  <div class="card-body">
    <%= link_to like_path(candidate), class: "like", method: :put do %>
      <button type="button" class="btn btn-primary" style="width:18rem">
      Vote!
      </button>
    <% end %>
  </div>
</div>

<% end %>

app/views/elections/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to VoteGems </h1>
</div>
<br></br>
<div class="d-flex align-items-center justify-content-center">
    <h3>Search for public Elections...</h3>
</div>

<%= form_tag search_elections_path, :method => 'get' do %>
    <div class="d-flex align-items-center justify-content-center" style="width:100%;">
        <%= text_field_tag :search, params[:search], style:"width:70%;"%>
    </div>
    <div class="d-flex align-items-center justify-content-center">
    <%= submit_tag "Search" %>
    </div>
<% end %>

app/views/elections/new.html.erb
<h1>Create A New Election</h1>
<%= form_with model: @election, url: create_path do |form| %>

    <% if form.object.errors.any? %>  
        <div class="alert alert-danger">
            <% @election.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <%end%>

   <div class="mb-3">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control", placeholder: "Election Title" %>
    </div>
    <div class="mb-3">
        <%= form.label "Is this a Public Election?" %>
        <%= form.check_box :ispublic%>
    </div>
    <div class="mb-3">
        <%= form.label "Participants" %>
        <h6>Please enter each email followed by ','</h6>
        <%= form.text_field :participants, class: "form-control", placeholder: "steve@gmail.com,jimjoe@yahoo.net,etc..." %>
    </div>

    <div class="mb-3">
        <%= form.submit "Create", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/elections/search.html.erb
<h1>you searched for "<%= params[:search] %>"</h1>
<% if @searchterm.empty? %>
  <h3 style="color:blue;">No Availiable Elections</h3>
<% else %>
  <% @searchterm.each do |election| %>

  <div class="card">
    <div class="card-body">
      <h5 style= "float:left;"><%= election.title %></h5>
      <%= link_to "View", select_elections_path(election), class: "btn btn-primary", style:"float:right;"%> 
    </div>
  </div>

  <% end %>
<% end %>

app/views/elections/select.html.erb
<%= session[:election_id] %>
<% @candidates.each do |element| %>

<div class="card" style="width: 20rem; margin: 10px; float:left;">
  <img class="card-img-top" src=<%= element.image %> alt="Card image cap" style="width:300px;height:300px;">
  <div class="card-body">
    <h5 class="card-title"><%= element.name %></h5>
    <h5 class="card-title"><%= element.score %></h5>
  </div>
  <div class="card-body">
    
  </div>
</div>

app/views/elections/view.html.erb
<h1>User Created Elections</h1>
<%if @createdbyelections.empty? %>
  <h3 style="color:blue;">No Availiable Elections</h3>
<% else %>
  <% @createdbyelections.each do |election| %>

  <div class="card">
    <div class="card-body">
      <h5 style= "float:left;"><%= election.title %></h5>
      <%= link_to "View", select_elections_path(election), class: "btn btn-primary", style:"float:right;"%> 
    </div>
  </div>

  <% end %>
<% end %>

<br></br>

<h1>Public Elections</h1>

<%if @publicelections.empty? %>
  <h3 style="color:blue;">No Availiable Elections</h3>
<% else %>
  <% @publicelections.each do |election| %>

  <div class="card">
    <div class="card-body">
      <h5 style= "float:left;"><%= election.title %></h5>
      <%= link_to "View", select_elections_path(election), class: "btn btn-primary", style:"float:right;"%> 
    </div>
  </div>

  <% end %>
<% end %>

<br></br>

<h1>Your Private Elections</h1>

<%if @privelections.empty? %>
  <h3 style="color:blue;">No Availiable Elections</h3>
<% else %>
  <% @privelections.each do |election| %>

  <div class="card">
    <div class="card-body">
      <h5 style= "float:left;"><%= election.title %></h5>
      <%= link_to "View", select_elections_path(election), class: "btn btn-primary", style:"float:right;"%> 
    </div>
  </div>

  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteGems</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <%= render partial: "shared/navbar"%>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Please Enter New Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    
    <% if form.object.errors.any? %>  
        <div class="alert alert-danger">
            <% @user.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <%end%>

    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <%= form.label :password_confirmation %>
    <div class="mb-3">
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Your Password?</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "abc@testing.com" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
        <!--<a class="navbar-brand" href="/">Navbar</a>-->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Create", create_path, class: "nav-link" %>
                    <!--<a class="nav-link active" aria-current="page" href="/">Home</a>-->
                </li>
                <li class="nav-item">
                    <%= link_to "Elections", view_elections_path, class: "nav-link" %>
                    <!--<a class="nav-link-about" href="/about">About</a>-->
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                    <!--<a class="nav-link-about" href="/about">About</a>-->
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <% if Current.user %>
                    <li class="nav-item">
                        <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-secondary" %>
                    </li>
                    <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign up", sign_up_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign in", sign_in_path, class:"nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>